//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quasar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quasar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mod Manually.
        /// </summary>
        public static string Library_Button_AddModManually {
            get {
                return ResourceManager.GetString("Library_Button_AddModManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Transfer.
        /// </summary>
        public static string Library_Button_StartTransfer {
            get {
                return ResourceManager.GetString("Library_Button_StartTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Library_Header_Actions {
            get {
                return ResourceManager.GetString("Library_Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Library_Header_Category {
            get {
                return ResourceManager.GetString("Library_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modification.
        /// </summary>
        public static string Library_Header_Date {
            get {
                return ResourceManager.GetString("Library_Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Name.
        /// </summary>
        public static string Library_Header_ModName {
            get {
                return ResourceManager.GetString("Library_Header_ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Library_Header_Type {
            get {
                return ResourceManager.GetString("Library_Header_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please download some mods from Gamebanana using the Quasar Download Button.
        /// </summary>
        public static string Library_Label_DownloadWarning {
            get {
                return ResourceManager.GetString("Library_Label_DownloadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Transferred and Reassigned.
        /// </summary>
        public static string Library_Label_EditedTransferDisabled {
            get {
                return ResourceManager.GetString("Library_Label_EditedTransferDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred and Reassigned.
        /// </summary>
        public static string Library_Label_EditedTransferEnabled {
            get {
                return ResourceManager.GetString("Library_Label_EditedTransferEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Transferred.
        /// </summary>
        public static string Library_Label_TransferDisabled {
            get {
                return ResourceManager.GetString("Library_Label_TransferDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred.
        /// </summary>
        public static string Library_Label_TransferEnabled {
            get {
                return ResourceManager.GetString("Library_Label_TransferEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string MainUI_AssignmentTabHeader {
            get {
                return ResourceManager.GetString("MainUI_AssignmentTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Manager.
        /// </summary>
        public static string MainUI_FileManagerTabHeader {
            get {
                return ResourceManager.GetString("MainUI_FileManagerTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string MainUI_LibraryTabHeader {
            get {
                return ResourceManager.GetString("MainUI_LibraryTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainUI_SettingsTabHeader {
            get {
                return ResourceManager.GetString("MainUI_SettingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Modal_Label_DefaultCancel {
            get {
                return ResourceManager.GetString("Modal_Label_DefaultCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Modal_Label_DefaultOK {
            get {
                return ResourceManager.GetString("Modal_Label_DefaultOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Files.
        /// </summary>
        public static string ModListItem_Button_EditFiles {
            get {
                return ResourceManager.GetString("ModListItem_Button_EditFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Mod.
        /// </summary>
        public static string ModListItem_Button_UpdateMod {
            get {
                return ResourceManager.GetString("ModListItem_Button_UpdateMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this mod.
        /// </summary>
        public static string ModListItem_DeleteModAction {
            get {
                return ResourceManager.GetString("ModListItem_DeleteModAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creators : .
        /// </summary>
        public static string ModListItem_Label_Author {
            get {
                return ResourceManager.GetString("ModListItem_Label_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed.
        /// </summary>
        public static string ModListItem_Label_DownloadFailed {
            get {
                return ResourceManager.GetString("ModListItem_Label_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Count : .
        /// </summary>
        public static string ModListItem_Label_UpdateCount {
            get {
                return ResourceManager.GetString("ModListItem_Label_UpdateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Control : .
        /// </summary>
        public static string ModListItem_Label_VersionControl {
            get {
                return ResourceManager.GetString("ModListItem_Label_VersionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string ModListItem_Time_Days {
            get {
                return ResourceManager.GetString("ModListItem_Time_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string ModListItem_Time_Hours {
            get {
                return ResourceManager.GetString("ModListItem_Time_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A long time ago.
        /// </summary>
        public static string ModListItem_Time_Long {
            get {
                return ResourceManager.GetString("ModListItem_Time_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A day ago.
        /// </summary>
        public static string ModListItem_Time_OneDay {
            get {
                return ResourceManager.GetString("ModListItem_Time_OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An hour ago.
        /// </summary>
        public static string ModListItem_Time_OneHour {
            get {
                return ResourceManager.GetString("ModListItem_Time_OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently.
        /// </summary>
        public static string ModListItem_Time_Recently {
            get {
                return ResourceManager.GetString("ModListItem_Time_Recently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar.
        /// </summary>
        public static string Quasar_WindowTitle {
            get {
                return ResourceManager.GetString("Quasar_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Installation Folder.
        /// </summary>
        public static string Settings_Button_MoveInstallFolder {
            get {
                return ResourceManager.GetString("Settings_Button_MoveInstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test and Save FTP Info.
        /// </summary>
        public static string Settings_Button_ValidateFTP {
            get {
                return ResourceManager.GetString("Settings_Button_ValidateFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this button to move all mods to a new location on your computer.
        /// </summary>
        public static string Settings_Comment_AskMoveInstall {
            get {
                return ResourceManager.GetString("Settings_Comment_AskMoveInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Switch&apos;s IP address.
        /// </summary>
        public static string Settings_Comment_FtpIP {
            get {
                return ResourceManager.GetString("Settings_Comment_FtpIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in your password if you&apos;ve enabled authentification on your Switch.
        /// </summary>
        public static string Settings_Comment_FtpPassword {
            get {
                return ResourceManager.GetString("Settings_Comment_FtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Switch&apos;s FTP Server Port (usually 5000).
        /// </summary>
        public static string Settings_Comment_FtpPort {
            get {
                return ResourceManager.GetString("Settings_Comment_FtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in your username if you&apos;ve enabled authentification on your Switch.
        /// </summary>
        public static string Settings_Comment_FtpUsername {
            get {
                return ResourceManager.GetString("Settings_Comment_FtpUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option to change Quasar&apos;s display language
        ///The app will need to be rebooted to see the change.
        /// </summary>
        public static string Settings_Comment_Language {
            get {
                return ResourceManager.GetString("Settings_Comment_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this to have all the mods on your Switch be only managed by Quasar.
        /// </summary>
        public static string Settings_Comment_ManageAllMods {
            get {
                return ResourceManager.GetString("Settings_Comment_ManageAllMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if you&apos;d rather transfer files wirelessly through FTP or via a plugged in SD.
        /// </summary>
        public static string Settings_Comment_PreferredTransferMethod {
            get {
                return ResourceManager.GetString("Settings_Comment_PreferredTransferMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this to be warned when deleting Mods.
        /// </summary>
        public static string Settings_Comment_SupressModDeletion {
            get {
                return ResourceManager.GetString("Settings_Comment_SupressModDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this button to verify that the Switch&apos;s FTP is working and to enable FTP transfers if successful.
        /// </summary>
        public static string Settings_Comment_TestFTP {
            get {
                return ResourceManager.GetString("Settings_Comment_TestFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Settings_Header_ApplicationSettings {
            get {
                return ResourceManager.GetString("Settings_Header_ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Transfer Settings.
        /// </summary>
        public static string Settings_Header_FileTransfer {
            get {
                return ResourceManager.GetString("Settings_Header_FileTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Settings.
        /// </summary>
        public static string Settings_Header_FtpSettings {
            get {
                return ResourceManager.GetString("Settings_Header_FtpSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string Settings_Header_Toggles {
            get {
                return ResourceManager.GetString("Settings_Header_Toggles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version.
        /// </summary>
        public static string Settings_Label_AppVersion {
            get {
                return ResourceManager.GetString("Settings_Label_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch&apos;s IP Address.
        /// </summary>
        public static string Settings_Label_FtpIP {
            get {
                return ResourceManager.GetString("Settings_Label_FtpIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Password.
        /// </summary>
        public static string Settings_Label_FtpPassword {
            get {
                return ResourceManager.GetString("Settings_Label_FtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch&apos;s FTP Port.
        /// </summary>
        public static string Settings_Label_FtpPort {
            get {
                return ResourceManager.GetString("Settings_Label_FtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Settings_Label_FtpUsername {
            get {
                return ResourceManager.GetString("Settings_Label_FtpUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Language.
        /// </summary>
        public static string Settings_Label_Language {
            get {
                return ResourceManager.GetString("Settings_Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage All Mods.
        /// </summary>
        public static string Settings_Label_ManageAllMods {
            get {
                return ResourceManager.GetString("Settings_Label_ManageAllMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Method.
        /// </summary>
        public static string Settings_Label_PreferredTransferMethod {
            get {
                return ResourceManager.GetString("Settings_Label_PreferredTransferMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Deletion.
        /// </summary>
        public static string Settings_Label_SupressModDeletion {
            get {
                return ResourceManager.GetString("Settings_Label_SupressModDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown Quasar.
        /// </summary>
        public static string Settings_Modal_Button_ShutdownWarning {
            get {
                return ResourceManager.GetString("Settings_Modal_Button_ShutdownWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change where Quasar stores it&apos;s files ? 
        ///It will take some time to transfer then will shutdown..
        /// </summary>
        public static string Settings_Modal_Content_AskMoveInstall {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_AskMoveInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while Quasar attempts to connect to the Switch.
        /// </summary>
        public static string Settings_Modal_Content_ConnectionWait {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_ConnectionWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is in progress, please wait for it to finish.
        /// </summary>
        public static string Settings_Modal_Content_MovingInstall {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_MovingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar will now close to process this change.
        /// </summary>
        public static string Settings_Modal_Content_ShutdownWarning {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_ShutdownWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the Switch is successful 
        ///you can now use FTP when transferring !.
        /// </summary>
        public static string Settings_Modal_Content_SuccessfulConnection {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_SuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the Switch is unsuccessful 
        ///please check the address and Username/Password if you have them,
        ///also check that your Switch is reachable.
        /// </summary>
        public static string Settings_Modal_Content_UnsuccessfulConnection {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_UnsuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address is not valid, please check that
        ///you have entered the right IP/Port.
        ///Also check that your FTP server is running.
        /// </summary>
        public static string Settings_Modal_Content_WrongIpFormat {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_WrongIpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown Quasar.
        /// </summary>
        public static string Settings_Modal_OkButton_MovingInstall {
            get {
                return ResourceManager.GetString("Settings_Modal_OkButton_MovingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Change.
        /// </summary>
        public static string Settings_Modal_Title_AskMoveInstall {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_AskMoveInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Test.
        /// </summary>
        public static string Settings_Modal_Title_ConnectionWait {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_ConnectionWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving files.
        /// </summary>
        public static string Settings_Modal_Title_MovingInstall {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_MovingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string Settings_Modal_Title_ShutdownWarning {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_ShutdownWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Settings_Modal_Title_SuccessfulConnection {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_SuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string Settings_Modal_Title_UnsuccessfulConnection {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_UnsuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Info.
        /// </summary>
        public static string Settings_Modal_Title_WrongIpFormat {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_WrongIpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless (FTP)=FTP,Wired (SD)=SD.
        /// </summary>
        public static string Settings_Values_PreferredTransferMethod {
            get {
                return ResourceManager.GetString("Settings_Values_PreferredTransferMethod", resourceCulture);
            }
        }
    }
}
