//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quasar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quasar.Properties.Resources.fr", typeof(Resources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas d&apos;élément.
        /// </summary>
        public static string Assignment_Label_NoElement {
            get {
                return ResourceManager.GetString("Assignment_Label_NoElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de slot.
        /// </summary>
        public static string Assignment_Label_NoSlot {
            get {
                return ResourceManager.GetString("Assignment_Label_NoSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez attendre que Quasar scanne les contenus du mod.
        /// </summary>
        public static string Assignment_Modal_ScanContent {
            get {
                return ResourceManager.GetString("Assignment_Modal_ScanContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur inattendue est survenue.
        ///Il n&apos;y a peut être pas de fichiers à scanner ou une erreur inattendue s&apos;est produite..
        /// </summary>
        public static string Assignment_Modal_ScanErrorContent {
            get {
                return ResourceManager.GetString("Assignment_Modal_ScanErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de scan.
        /// </summary>
        public static string Assignment_Modal_ScanErrorTitle {
            get {
                return ResourceManager.GetString("Assignment_Modal_ScanErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar  a scanné le mod et ses  
        ///contenus éditables sont affichés ici.
        /// </summary>
        public static string Assignment_Modal_ScanFinishedContent {
            get {
                return ResourceManager.GetString("Assignment_Modal_ScanFinishedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan terminé.
        /// </summary>
        public static string Assignment_Modal_ScanFinishedTitle {
            get {
                return ResourceManager.GetString("Assignment_Modal_ScanFinishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan en cours.
        /// </summary>
        public static string Assignment_Modal_ScanTitle {
            get {
                return ResourceManager.GetString("Assignment_Modal_ScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner les fichiers.
        /// </summary>
        public static string Assignments_Button_ScanFiles {
            get {
                return ResourceManager.GetString("Assignments_Button_ScanFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types Groupés.
        /// </summary>
        public static string Assignments_Label_GroupTypes {
            get {
                return ResourceManager.GetString("Assignments_Label_GroupTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affichage des attributions pour : .
        /// </summary>
        public static string Assignments_Label_ModName {
            get {
                return ResourceManager.GetString("Assignments_Label_ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer les fichiers.
        /// </summary>
        public static string FileManagement_Button_ChangeFiles {
            get {
                return ResourceManager.GetString("FileManagement_Button_ChangeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer des fichiers.
        /// </summary>
        public static string FileManagement_Button_ImportFiles {
            get {
                return ResourceManager.GetString("FileManagement_Button_ImportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le dossier du mod.
        /// </summary>
        public static string FileManagement_Button_OpenFolder {
            get {
                return ResourceManager.GetString("FileManagement_Button_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string FileManagement_Button_SaveModName {
            get {
                return ResourceManager.GetString("FileManagement_Button_SaveModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du mod :.
        /// </summary>
        public static string FileManagement_Label_ModName {
            get {
                return ResourceManager.GetString("FileManagement_Label_ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout manuel.
        /// </summary>
        public static string Library_Button_AddModManually {
            get {
                return ResourceManager.GetString("Library_Button_AddModManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer le transfert.
        /// </summary>
        public static string Library_Button_StartTransfer {
            get {
                return ResourceManager.GetString("Library_Button_StartTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Library_Header_Actions {
            get {
                return ResourceManager.GetString("Library_Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string Library_Header_Category {
            get {
                return ResourceManager.GetString("Library_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière modification.
        /// </summary>
        public static string Library_Header_Date {
            get {
                return ResourceManager.GetString("Library_Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du Mod.
        /// </summary>
        public static string Library_Header_ModName {
            get {
                return ResourceManager.GetString("Library_Header_ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Library_Header_Type {
            get {
                return ResourceManager.GetString("Library_Header_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez télécharger des mods depuis le site Gamebanana.com en utilisant les boutons Quasar.
        /// </summary>
        public static string Library_Label_DownloadWarning {
            get {
                return ResourceManager.GetString("Library_Label_DownloadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transféré et réassigné.
        /// </summary>
        public static string Library_Label_EditedTransferEnabled {
            get {
                return ResourceManager.GetString("Library_Label_EditedTransferEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non transféré.
        /// </summary>
        public static string Library_Label_TransferDisabled {
            get {
                return ResourceManager.GetString("Library_Label_TransferDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transféré.
        /// </summary>
        public static string Library_Label_TransferEnabled {
            get {
                return ResourceManager.GetString("Library_Label_TransferEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar est en train d&apos;importer les fichiers sélectionnés.
        /// </summary>
        public static string Library_Modal_Content_ImportFiles {
            get {
                return ResourceManager.GetString("Library_Modal_Content_ImportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar n&apos;a pas réussi à importer les fichiers..
        /// </summary>
        public static string Library_Modal_Content_ImportFiles_Failure {
            get {
                return ResourceManager.GetString("Library_Modal_Content_ImportFiles_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar a terminé l&apos;import avec succès.
        /// </summary>
        public static string Library_Modal_Content_ImportFiles_Success {
            get {
                return ResourceManager.GetString("Library_Modal_Content_ImportFiles_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Library_Modal_DeleteCancel {
            get {
                return ResourceManager.GetString("Library_Modal_DeleteCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etes-vous sûr de vouloir supprimer ce mod ? 
        ///Ses fichiers et informations seront supprimées de Quasar..
        /// </summary>
        public static string Library_Modal_DeleteContent {
            get {
                return ResourceManager.GetString("Library_Modal_DeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je suis sûr.
        /// </summary>
        public static string Library_Modal_DeleteOK {
            get {
                return ResourceManager.GetString("Library_Modal_DeleteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression de Mod.
        /// </summary>
        public static string Library_Modal_DeleteTitle {
            get {
                return ResourceManager.GetString("Library_Modal_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import en cours.
        /// </summary>
        public static string Library_Modal_Title_ImportFiles {
            get {
                return ResourceManager.GetString("Library_Modal_Title_ImportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur d&apos;import.
        /// </summary>
        public static string Library_Modal_Title_ImportFiles_Failure {
            get {
                return ResourceManager.GetString("Library_Modal_Title_ImportFiles_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import réussi.
        /// </summary>
        public static string Library_Modal_Title_ImportFiles_Success {
            get {
                return ResourceManager.GetString("Library_Modal_Title_ImportFiles_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Library_Modal_TransferWarningCancel {
            get {
                return ResourceManager.GetString("Library_Modal_TransferWarningCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez sélectionné l&apos;option &quot;Gérer tous les mods&quot;
        ///Cela indique à Quasar de supprimer tous les fichiers qu&apos;il ne gère pas.
        ///Tous les mods non transférés par Quasar seront supprimés.
        /// </summary>
        public static string Library_Modal_TransferWarningContent {
            get {
                return ResourceManager.GetString("Library_Modal_TransferWarningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je suis sûr.
        /// </summary>
        public static string Library_Modal_TransferWarningOK {
            get {
                return ResourceManager.GetString("Library_Modal_TransferWarningOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avertissement de transfert.
        /// </summary>
        public static string Library_Modal_TransferWarningTitle {
            get {
                return ResourceManager.GetString("Library_Modal_TransferWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributions.
        /// </summary>
        public static string MainUI_AssignmentTabHeader {
            get {
                return ResourceManager.GetString("MainUI_AssignmentTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers.
        /// </summary>
        public static string MainUI_FileManagerTabHeader {
            get {
                return ResourceManager.GetString("MainUI_FileManagerTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librairie.
        /// </summary>
        public static string MainUI_LibraryTabHeader {
            get {
                return ResourceManager.GetString("MainUI_LibraryTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar est une application qui permet de gérer les 
        ///fichiers de mods pour vous. Les mods fonctionnent sur des Switch 
        ///disposant d&apos;un CFW (Firmware custom). Si vous n&apos;en disposez pas,
        ///Quasar ne pourra rien pour vous..
        /// </summary>
        public static string MainUI_Modal_CFWContent {
            get {
                return ResourceManager.GetString("MainUI_Modal_CFWContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma Switch a un CFW.
        /// </summary>
        public static string MainUI_Modal_CFWOK {
            get {
                return ResourceManager.GetString("MainUI_Modal_CFWOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar s&apos;est mis à jour avec succès.
        /// </summary>
        public static string MainUI_Modal_RecoverFinishedContent {
            get {
                return ResourceManager.GetString("MainUI_Modal_RecoverFinishedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour terminée.
        /// </summary>
        public static string MainUI_Modal_RecoverFinishedTitle {
            get {
                return ResourceManager.GetString("MainUI_Modal_RecoverFinishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez patienter, Quasar récupère
        ///les fichiers d&apos;une installation précédente.
        /// </summary>
        public static string MainUI_Modal_RecoverProgressContent {
            get {
                return ResourceManager.GetString("MainUI_Modal_RecoverProgressContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récupération de données.
        /// </summary>
        public static string MainUI_Modal_RecoverProgressTitle {
            get {
                return ResourceManager.GetString("MainUI_Modal_RecoverProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar à fini son processus de mise à jour avec succès.
        /// </summary>
        public static string MainUI_Modal_UpdateFinishedContent {
            get {
                return ResourceManager.GetString("MainUI_Modal_UpdateFinishedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour terminée.
        /// </summary>
        public static string MainUI_Modal_UpdateFinishedTitle {
            get {
                return ResourceManager.GetString("MainUI_Modal_UpdateFinishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez patienter, Quasar se met à jour.
        /// </summary>
        public static string MainUI_Modal_UpdateProgressContent {
            get {
                return ResourceManager.GetString("MainUI_Modal_UpdateProgressContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour.
        /// </summary>
        public static string MainUI_Modal_UpdateProgressTitle {
            get {
                return ResourceManager.GetString("MainUI_Modal_UpdateProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string MainUI_SettingsTabHeader {
            get {
                return ResourceManager.GetString("MainUI_SettingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Modal_Label_DefaultCancel {
            get {
                return ResourceManager.GetString("Modal_Label_DefaultCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Modal_Label_DefaultOK {
            get {
                return ResourceManager.GetString("Modal_Label_DefaultOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléchargement.
        /// </summary>
        public static string ModItem_Label_Downloading {
            get {
                return ResourceManager.GetString("ModItem_Label_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction.
        /// </summary>
        public static string ModItem_Label_Extracting {
            get {
                return ResourceManager.GetString("ModItem_Label_Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez patienter.
        /// </summary>
        public static string ModItem_Label_ExtractWait {
            get {
                return ResourceManager.GetString("ModItem_Label_ExtractWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous!.
        /// </summary>
        public static string ModItem_Label_ManualAuthor {
            get {
                return ResourceManager.GetString("ModItem_Label_ManualAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;avez importé.
        /// </summary>
        public static string ModItem_Label_ManualAuthorRole {
            get {
                return ResourceManager.GetString("ModItem_Label_ManualAuthorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacement des fichiers.
        /// </summary>
        public static string ModItem_Label_Processing {
            get {
                return ResourceManager.GetString("ModItem_Label_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter ce mod à la liste de transfert.
        /// </summary>
        public static string ModItem_Tooltip_AddMod {
            get {
                return ResourceManager.GetString("ModItem_Tooltip_AddMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer l&apos;assignation du mod (Slot, élément remplacé etc.).
        /// </summary>
        public static string ModItem_Tooltip_AssignMod {
            get {
                return ResourceManager.GetString("ModItem_Tooltip_AssignMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer ce mod de Quasar.
        /// </summary>
        public static string ModItem_Tooltip_DeleteMod {
            get {
                return ResourceManager.GetString("ModItem_Tooltip_DeleteMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer ce mod de la liste de transfert.
        /// </summary>
        public static string ModItem_Tooltip_RemoveMod {
            get {
                return ResourceManager.GetString("ModItem_Tooltip_RemoveMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renommer ce mod.
        /// </summary>
        public static string ModItem_Tooltip_RenameMod {
            get {
                return ResourceManager.GetString("ModItem_Tooltip_RenameMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder le nouveau nom.
        /// </summary>
        public static string ModItem_Tooltip_ValidateRename {
            get {
                return ResourceManager.GetString("ModItem_Tooltip_ValidateRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer des fichiers.
        /// </summary>
        public static string ModListItem_Button_EditFiles {
            get {
                return ResourceManager.GetString("ModListItem_Button_EditFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour.
        /// </summary>
        public static string ModListItem_Button_UpdateMod {
            get {
                return ResourceManager.GetString("ModListItem_Button_UpdateMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer ce mod.
        /// </summary>
        public static string ModListItem_DeleteModAction {
            get {
                return ResourceManager.GetString("ModListItem_DeleteModAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créateurs : .
        /// </summary>
        public static string ModListItem_Label_Author {
            get {
                return ResourceManager.GetString("ModListItem_Label_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléchargement échoué.
        /// </summary>
        public static string ModListItem_Label_DownloadFailed {
            get {
                return ResourceManager.GetString("ModListItem_Label_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de MàJ : .
        /// </summary>
        public static string ModListItem_Label_UpdateCount {
            get {
                return ResourceManager.GetString("ModListItem_Label_UpdateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions : .
        /// </summary>
        public static string ModListItem_Label_VersionControl {
            get {
                return ResourceManager.GetString("ModListItem_Label_VersionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a {0} jours.
        /// </summary>
        public static string ModListItem_Time_Days {
            get {
                return ResourceManager.GetString("ModListItem_Time_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a {0} heures.
        /// </summary>
        public static string ModListItem_Time_Hours {
            get {
                return ResourceManager.GetString("ModListItem_Time_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a longtemps.
        /// </summary>
        public static string ModListItem_Time_Long {
            get {
                return ResourceManager.GetString("ModListItem_Time_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a un jour.
        /// </summary>
        public static string ModListItem_Time_OneDay {
            get {
                return ResourceManager.GetString("ModListItem_Time_OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a une heure.
        /// </summary>
        public static string ModListItem_Time_OneHour {
            get {
                return ResourceManager.GetString("ModListItem_Time_OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récemment.
        /// </summary>
        public static string ModListItem_Time_Recently {
            get {
                return ResourceManager.GetString("ModListItem_Time_Recently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar est actuellement actif.\rQuitter l&apos;application maintenant pourra provoquer des erreurs futures..
        /// </summary>
        public static string Quasar_Modal_Content_Exit {
            get {
                return ResourceManager.GetString("Quasar_Modal_Content_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir quitter ?.
        /// </summary>
        public static string Quasar_Modal_Title_Exit {
            get {
                return ResourceManager.GetString("Quasar_Modal_Title_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar.
        /// </summary>
        public static string Quasar_WindowTitle {
            get {
                return ResourceManager.GetString("Quasar_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacer le dossier d&apos;installation.
        /// </summary>
        public static string Settings_Button_MoveInstallFolder {
            get {
                return ResourceManager.GetString("Settings_Button_MoveInstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualiser les disques.
        /// </summary>
        public static string Settings_Button_Refresh {
            get {
                return ResourceManager.GetString("Settings_Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester et valider les paramètres FTP.
        /// </summary>
        public static string Settings_Button_ValidateFTP {
            get {
                return ResourceManager.GetString("Settings_Button_ValidateFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisez cette option pour déplacer tous les fichiers de mods dans un autre dossier de l&apos;ordinateur.
        /// </summary>
        public static string Settings_Comment_AskMoveInstall {
            get {
                return ResourceManager.GetString("Settings_Comment_AskMoveInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer le chemin d&apos;accès au dossier dans lequel Quasar effectuera le transfert de mods. Veuillez appuyer sur Entrée pour valider le nouvel emplacement..
        /// </summary>
        public static string Settings_Comment_Diskpath {
            get {
                return ResourceManager.GetString("Settings_Comment_Diskpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez remplir ce champ avec l&apos;adresse IP de la Switch.
        /// </summary>
        public static string Settings_Comment_FtpIP {
            get {
                return ResourceManager.GetString("Settings_Comment_FtpIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez remplir ce champ avec le mot de passe défini dans la configuration du serveur FTP si l&apos;authentification est activée.
        /// </summary>
        public static string Settings_Comment_FtpPassword {
            get {
                return ResourceManager.GetString("Settings_Comment_FtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez remplir ce champ avec le port utilisé par le serveur FTP de la Switch.
        /// </summary>
        public static string Settings_Comment_FtpPort {
            get {
                return ResourceManager.GetString("Settings_Comment_FtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez remplir ce champ avec l&apos;utilisateur défini dans la configuration du serveur FTP si l&apos;authentification est activée.
        /// </summary>
        public static string Settings_Comment_FtpUsername {
            get {
                return ResourceManager.GetString("Settings_Comment_FtpUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez une option pour changer la langue d&apos;affichage
        ///L&apos;app doit être redémarrer pour que le changement soit effectif.
        /// </summary>
        public static string Settings_Comment_Language {
            get {
                return ResourceManager.GetString("Settings_Comment_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activez cette option pour que le dossier de mods de la Switch soit uniquement géré par Quasar.
        /// </summary>
        public static string Settings_Comment_ManageAllMods {
            get {
                return ResourceManager.GetString("Settings_Comment_ManageAllMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez changer l&apos;emplacement des mods sur la SD avec ce champ. Veuillez appuyer sur Entrée pour valider le nouvel emplacement..
        /// </summary>
        public static string Settings_Comment_ModsPath {
            get {
                return ResourceManager.GetString("Settings_Comment_ModsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner si vous préférez transférer les fichiers par FTP sans-fil ou avec un transfert local sur une SD connectée.
        /// </summary>
        public static string Settings_Comment_PreferredTransferMethod {
            get {
                return ResourceManager.GetString("Settings_Comment_PreferredTransferMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez la SD sur laquelle vous voulez transférer les fichiers.
        /// </summary>
        public static string Settings_Comment_SDSelect {
            get {
                return ResourceManager.GetString("Settings_Comment_SDSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activez ceci pour être prévenu lorsque le nettoyage du dossier de mods sera fait.
        /// </summary>
        public static string Settings_Comment_SuppressManageWarning {
            get {
                return ResourceManager.GetString("Settings_Comment_SuppressManageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activez cette option pour être prévenu de la supression d&apos;un mod.
        /// </summary>
        public static string Settings_Comment_SupressModDeletion {
            get {
                return ResourceManager.GetString("Settings_Comment_SupressModDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisez cette option pour valider les paramètres FTP et autoriser les transferts FTP.
        /// </summary>
        public static string Settings_Comment_TestFTP {
            get {
                return ResourceManager.GetString("Settings_Comment_TestFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Settings_Header_ApplicationSettings {
            get {
                return ResourceManager.GetString("Settings_Header_ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres de transfert.
        /// </summary>
        public static string Settings_Header_FileTransfer {
            get {
                return ResourceManager.GetString("Settings_Header_FileTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres FTP.
        /// </summary>
        public static string Settings_Header_FtpSettings {
            get {
                return ResourceManager.GetString("Settings_Header_FtpSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres d&apos;avertissements.
        /// </summary>
        public static string Settings_Header_Toggles {
            get {
                return ResourceManager.GetString("Settings_Header_Toggles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version de l&apos;application.
        /// </summary>
        public static string Settings_Label_AppVersion {
            get {
                return ResourceManager.GetString("Settings_Label_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement Disque.
        /// </summary>
        public static string Settings_Label_Diskpath {
            get {
                return ResourceManager.GetString("Settings_Label_Diskpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse IP de la Switch.
        /// </summary>
        public static string Settings_Label_FtpIP {
            get {
                return ResourceManager.GetString("Settings_Label_FtpIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Settings_Label_FtpPassword {
            get {
                return ResourceManager.GetString("Settings_Label_FtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port FTP.
        /// </summary>
        public static string Settings_Label_FtpPort {
            get {
                return ResourceManager.GetString("Settings_Label_FtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string Settings_Label_FtpUsername {
            get {
                return ResourceManager.GetString("Settings_Label_FtpUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue de l&apos;application.
        /// </summary>
        public static string Settings_Label_Language {
            get {
                return ResourceManager.GetString("Settings_Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer tous les mods.
        /// </summary>
        public static string Settings_Label_ManageAllMods {
            get {
                return ResourceManager.GetString("Settings_Label_ManageAllMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répertoire de mods.
        /// </summary>
        public static string Settings_Label_ModsPath {
            get {
                return ResourceManager.GetString("Settings_Label_ModsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Méthode de transfert.
        /// </summary>
        public static string Settings_Label_PreferredTransferMethod {
            get {
                return ResourceManager.GetString("Settings_Label_PreferredTransferMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélection de SD.
        /// </summary>
        public static string Settings_Label_SDSelect {
            get {
                return ResourceManager.GetString("Settings_Label_SDSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de tous les mods.
        /// </summary>
        public static string Settings_Label_SuppressManageWarning {
            get {
                return ResourceManager.GetString("Settings_Label_SuppressManageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supression de mods.
        /// </summary>
        public static string Settings_Label_SupressModDeletion {
            get {
                return ResourceManager.GetString("Settings_Label_SupressModDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer Quasar.
        /// </summary>
        public static string Settings_Modal_Button_ShutdownWarning {
            get {
                return ResourceManager.GetString("Settings_Modal_Button_ShutdownWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous changer l&apos;emplacement de stockage des mods ? 
        ///L&apos;opération peut être longue et Quasar se fermera ensuite..
        /// </summary>
        public static string Settings_Modal_Content_AskMoveInstall {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_AskMoveInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez attendre pendant que Quasar contacte votre Switch.
        /// </summary>
        public static string Settings_Modal_Content_ConnectionWait {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_ConnectionWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;opération est en cours, merci d&apos;attendre qu&apos;elle finisse.
        /// </summary>
        public static string Settings_Modal_Content_MovingInstall {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_MovingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar va se fermer pour effectuer le changement.
        /// </summary>
        public static string Settings_Modal_Content_ShutdownWarning {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_ShutdownWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion à la Switch réussie
        ///Le FTP sera maintenant activé pour les transferts.
        /// </summary>
        public static string Settings_Modal_Content_SuccessfulConnection {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_SuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion à la Switch échouée
        ///Veuillez vérifier les informations de connexion 
        ///Vérifiez aussi que votre Switch soit joignable.
        /// </summary>
        public static string Settings_Modal_Content_UnsuccessfulConnection {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_UnsuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse renseignée n&apos;est pas valide. Vérifiez 
        ///que la bonne IP et le bon port soient utilisés..
        /// </summary>
        public static string Settings_Modal_Content_WrongIpFormat {
            get {
                return ResourceManager.GetString("Settings_Modal_Content_WrongIpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer Quasar.
        /// </summary>
        public static string Settings_Modal_OkButton_MovingInstall {
            get {
                return ResourceManager.GetString("Settings_Modal_OkButton_MovingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changement d&apos;emplacement.
        /// </summary>
        public static string Settings_Modal_Title_AskMoveInstall {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_AskMoveInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test de connexion.
        /// </summary>
        public static string Settings_Modal_Title_ConnectionWait {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_ConnectionWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacement des fichiers.
        /// </summary>
        public static string Settings_Modal_Title_MovingInstall {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_MovingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt.
        /// </summary>
        public static string Settings_Modal_Title_ShutdownWarning {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_ShutdownWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succès.
        /// </summary>
        public static string Settings_Modal_Title_SuccessfulConnection {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_SuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de connexion.
        /// </summary>
        public static string Settings_Modal_Title_UnsuccessfulConnection {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_UnsuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations invalides.
        /// </summary>
        public static string Settings_Modal_Title_WrongIpFormat {
            get {
                return ResourceManager.GetString("Settings_Modal_Title_WrongIpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sans-fil (FTP)=FTP,Local (SD)=SD, Emplacement Disque=Disk.
        /// </summary>
        public static string Settings_Values_PreferredTransferMethod {
            get {
                return ResourceManager.GetString("Settings_Values_PreferredTransferMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les fichiers ont été copiés.
        /// </summary>
        public static string Transfer_Log_AllFilesCopied {
            get {
                return ResourceManager.GetString("Transfer_Log_AllFilesCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toutes les différences ont été supprimées.
        /// </summary>
        public static string Transfer_Log_AllFilesDeleted {
            get {
                return ResourceManager.GetString("Transfer_Log_AllFilesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nettoyage du dossier de mod.
        /// </summary>
        public static string Transfer_Log_Cleanup {
            get {
                return ResourceManager.GetString("Transfer_Log_Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le chemin disque renseigné n&apos;existe pas.
        /// </summary>
        public static string Transfer_Log_DiskPathUnavailable {
            get {
                return ResourceManager.GetString("Transfer_Log_DiskPathUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string Transfer_Log_Error {
            get {
                return ResourceManager.GetString("Transfer_Log_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de transfert pour certains fichiers.
        /// </summary>
        public static string Transfer_Log_FileError {
            get {
                return ResourceManager.GetString("Transfer_Log_FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers transférés pour {0}.
        /// </summary>
        public static string Transfer_Log_FinishedMod {
            get {
                return ResourceManager.GetString("Transfer_Log_FinishedMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de la connection..
        /// </summary>
        public static string Transfer_Log_FTPConnectionFail {
            get {
                return ResourceManager.GetString("Transfer_Log_FTPConnectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection réussie..
        /// </summary>
        public static string Transfer_Log_FTPConnectionSuccess {
            get {
                return ResourceManager.GetString("Transfer_Log_FTPConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essai de connection à la Switch....
        /// </summary>
        public static string Transfer_Log_FTPConnectionTest {
            get {
                return ResourceManager.GetString("Transfer_Log_FTPConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Transfer_Log_GeneralTransferError {
            get {
                return ResourceManager.GetString("Transfer_Log_GeneralTransferError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de transfert globale.
        /// </summary>
        public static string Transfer_Log_GlobalError {
            get {
                return ResourceManager.GetString("Transfer_Log_GlobalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Transfer_Log_Info {
            get {
                return ResourceManager.GetString("Transfer_Log_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun fichier à copier.
        /// </summary>
        public static string Transfer_Log_NoCopy {
            get {
                return ResourceManager.GetString("Transfer_Log_NoCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun fichier à supprimer.
        /// </summary>
        public static string Transfer_Log_NoDelete {
            get {
                return ResourceManager.GetString("Transfer_Log_NoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de lancement du transfert..
        /// </summary>
        public static string Transfer_Log_NoLaunch {
            get {
                return ResourceManager.GetString("Transfer_Log_NoLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune SD sélectionnée.
        /// </summary>
        public static string Transfer_Log_NoSDSelected {
            get {
                return ResourceManager.GetString("Transfer_Log_NoSDSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traitement  de ce que Quasar doit faire....
        /// </summary>
        public static string Transfer_Log_ProcessingLists {
            get {
                return ResourceManager.GetString("Transfer_Log_ProcessingLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Début du transfert :.
        /// </summary>
        public static string Transfer_Log_ProcessStart {
            get {
                return ResourceManager.GetString("Transfer_Log_ProcessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La SD Sélectionée n&apos;est pas disponible.
        /// </summary>
        public static string Transfer_Log_SelectedSDUnavailable {
            get {
                return ResourceManager.GetString("Transfer_Log_SelectedSDUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfert terminé.
        /// </summary>
        public static string Transfer_Log_TransferFinished {
            get {
                return ResourceManager.GetString("Transfer_Log_TransferFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} Fichiers.
        /// </summary>
        public static string Transfer_Step_Files {
            get {
                return ResourceManager.GetString("Transfer_Step_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminé.
        /// </summary>
        public static string Transfer_Step_FinishedStepText {
            get {
                return ResourceManager.GetString("Transfer_Step_FinishedStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut du transfert :.
        /// </summary>
        public static string Transfer_Step_Global {
            get {
                return ResourceManager.GetString("Transfer_Step_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape : {0}.
        /// </summary>
        public static string Transfer_Step_StepText {
            get {
                return ResourceManager.GetString("Transfer_Step_StepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-tâche : {0}.
        /// </summary>
        public static string Transfer_Step_SubStepText {
            get {
                return ResourceManager.GetString("Transfer_Step_SubStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfert des fichiers.
        /// </summary>
        public static string Transfer_Step_TransferingFilesStepText {
            get {
                return ResourceManager.GetString("Transfer_Step_TransferingFilesStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfert pour {0}.
        /// </summary>
        public static string Transfer_Step_TransferingFilesSubStepText {
            get {
                return ResourceManager.GetString("Transfer_Step_TransferingFilesSubStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer la fenêtre de transfert..
        /// </summary>
        public static string Transfer_Tooltip_CloseWindowButton {
            get {
                return ResourceManager.GetString("Transfer_Tooltip_CloseWindowButton", resourceCulture);
            }
        }
    }
}
