//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quasar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quasar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp; Package.
        /// </summary>
        public static string AddPackageTabHeader {
            get {
                return ResourceManager.GetString("AddPackageTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Assignment.
        /// </summary>
        public static string AssignmentTabHeader {
            get {
                return ResourceManager.GetString("AssignmentTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckModUpdateButton {
            get {
                return ResourceManager.GetString("CheckModUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Folders.
        /// </summary>
        public static string ClearQuasarFolderButton {
            get {
                return ResourceManager.GetString("ClearQuasarFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Browser.
        /// </summary>
        public static string FileBrowserHeader {
            get {
                return ResourceManager.GetString("FileBrowserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Management.
        /// </summary>
        public static string ManagementTabHeader {
            get {
                return ResourceManager.GetString("ManagementTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string ModAuthor {
            get {
                return ResourceManager.GetString("ModAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can filter things here.
        /// </summary>
        public static string ModFilterSelectText {
            get {
                return ResourceManager.GetString("ModFilterSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Information.
        /// </summary>
        public static string ModInformationHeader {
            get {
                return ResourceManager.GetString("ModInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ModStatus {
            get {
                return ResourceManager.GetString("ModStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a mod type.
        /// </summary>
        public static string ModTypeSelectText {
            get {
                return ResourceManager.GetString("ModTypeSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string ModVersion {
            get {
                return ResourceManager.GetString("ModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTabHeader {
            get {
                return ResourceManager.GetString("SettingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Test Download.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasar Mod Manager.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Control.
        /// </summary>
        public static string VersionInformationHeader {
            get {
                return ResourceManager.GetString("VersionInformationHeader", resourceCulture);
            }
        }
    }
}
