//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quasar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class SettingsDefinition : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsDefinition defaultInstance = ((SettingsDefinition)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsDefinition())));
        
        public static SettingsDefinition Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supress mod deletion warning")]
        public string SupressModDeletionName {
            get {
                return ((string)(this["SupressModDeletionName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enable this to supress the warning when deleting a mod")]
        public string SupressModDeletionComment {
            get {
                return ((string)(this["SupressModDeletionComment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SupressModDeletionValues {
            get {
                return ((string)(this["SupressModDeletionValues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supress build warning")]
        public string SupressBuildDeletionName {
            get {
                return ((string)(this["SupressBuildDeletionName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enable this to supress the warning when building")]
        public string SupressBuildDeletionComment {
            get {
                return ((string)(this["SupressBuildDeletionComment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SupressBuildDeletionValues {
            get {
                return ((string)(this["SupressBuildDeletionValues"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Quasar Version")]
        public string AppVersionName {
            get {
                return ((string)(this["AppVersionName"]));
            }
            set {
                this["AppVersionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppVersionComment {
            get {
                return ((string)(this["AppVersionComment"]));
            }
            set {
                this["AppVersionComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enable Internal Mod Types")]
        public string EnableIMTName {
            get {
                return ((string)(this["EnableIMTName"]));
            }
            set {
                this["EnableIMTName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enables a tab to configure types, for advanced users only")]
        public string EnableIMTComment {
            get {
                return ((string)(this["EnableIMTComment"]));
            }
            set {
                this["EnableIMTComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppVersionValues {
            get {
                return ((string)(this["AppVersionValues"]));
            }
            set {
                this["AppVersionValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Language")]
        public string LanguageName {
            get {
                return ((string)(this["LanguageName"]));
            }
            set {
                this["LanguageName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You can change the app\'s display language here")]
        public string LanguageComment {
            get {
                return ((string)(this["LanguageComment"]));
            }
            set {
                this["LanguageComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English=EN,Français=FR")]
        public string LanguageValues {
            get {
                return ((string)(this["LanguageValues"]));
            }
            set {
                this["LanguageValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EnableIMTValues {
            get {
                return ((string)(this["EnableIMTValues"]));
            }
            set {
                this["EnableIMTValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FTP Address")]
        public string FTPAddressName {
            get {
                return ((string)(this["FTPAddressName"]));
            }
            set {
                this["FTPAddressName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please enter the address in this format : [IP Address:Port] - Here is an example " +
            ": 192.168.0.100:500 ")]
        public string FTPAddressComment {
            get {
                return ((string)(this["FTPAddressComment"]));
            }
            set {
                this["FTPAddressComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTPAddressValues {
            get {
                return ((string)(this["FTPAddressValues"]));
            }
            set {
                this["FTPAddressValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FTP Username")]
        public string FTPUNName {
            get {
                return ((string)(this["FTPUNName"]));
            }
            set {
                this["FTPUNName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("If you have authentification enabled on your Switch, please enter the username he" +
            "re")]
        public string FTPUNComment {
            get {
                return ((string)(this["FTPUNComment"]));
            }
            set {
                this["FTPUNComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTPUNValues {
            get {
                return ((string)(this["FTPUNValues"]));
            }
            set {
                this["FTPUNValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FTP Password")]
        public string FTPPWName {
            get {
                return ((string)(this["FTPPWName"]));
            }
            set {
                this["FTPPWName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("If you have authentification enabled on your Switch, please enter the password he" +
            "re")]
        public string FTPPWComment {
            get {
                return ((string)(this["FTPPWComment"]));
            }
            set {
                this["FTPPWComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTPPWValues {
            get {
                return ((string)(this["FTPPWValues"]));
            }
            set {
                this["FTPPWValues"] = value;
            }
        }
    }
}
