//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quasar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class SettingsDefinition : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsDefinition defaultInstance = ((SettingsDefinition)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsDefinition())));
        
        public static SettingsDefinition Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supress mod deletion warning")]
        public string SupressModDeletionName {
            get {
                return ((string)(this["SupressModDeletionName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enable this to supress the warning when deleting a mod")]
        public string SupressModDeletionComment {
            get {
                return ((string)(this["SupressModDeletionComment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SupressModDeletionValues {
            get {
                return ((string)(this["SupressModDeletionValues"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Quasar Version")]
        public string AppVersionName {
            get {
                return ((string)(this["AppVersionName"]));
            }
            set {
                this["AppVersionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppVersionComment {
            get {
                return ((string)(this["AppVersionComment"]));
            }
            set {
                this["AppVersionComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppVersionValues {
            get {
                return ((string)(this["AppVersionValues"]));
            }
            set {
                this["AppVersionValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Language")]
        public string LanguageName {
            get {
                return ((string)(this["LanguageName"]));
            }
            set {
                this["LanguageName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You can change the app\'s display language here")]
        public string LanguageComment {
            get {
                return ((string)(this["LanguageComment"]));
            }
            set {
                this["LanguageComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English=EN,Français=FR")]
        public string LanguageValues {
            get {
                return ((string)(this["LanguageValues"]));
            }
            set {
                this["LanguageValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FTP Address")]
        public string FtpAddressName {
            get {
                return ((string)(this["FtpAddressName"]));
            }
            set {
                this["FtpAddressName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please enter the address in this format : [IP Address:Port] - Here is an example " +
            ": 192.168.0.100:500 ")]
        public string FtpAddressComment {
            get {
                return ((string)(this["FtpAddressComment"]));
            }
            set {
                this["FtpAddressComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USER=US")]
        public string FtpAddressValues {
            get {
                return ((string)(this["FtpAddressValues"]));
            }
            set {
                this["FtpAddressValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FTP Username")]
        public string FtpUsernameName {
            get {
                return ((string)(this["FtpUsernameName"]));
            }
            set {
                this["FtpUsernameName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("If you have authentification enabled on your Switch, please enter the username he" +
            "re")]
        public string FtpUsernameComment {
            get {
                return ((string)(this["FtpUsernameComment"]));
            }
            set {
                this["FtpUsernameComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USER=US")]
        public string FTPUsernameValues {
            get {
                return ((string)(this["FTPUsernameValues"]));
            }
            set {
                this["FTPUsernameValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FTP Password")]
        public string FtpPasswordName {
            get {
                return ((string)(this["FtpPasswordName"]));
            }
            set {
                this["FtpPasswordName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("If you have authentification enabled on your Switch, please enter the password he" +
            "re")]
        public string FtpPasswordComment {
            get {
                return ((string)(this["FtpPasswordComment"]));
            }
            set {
                this["FtpPasswordComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USER=US")]
        public string FtpPasswordValues {
            get {
                return ((string)(this["FtpPasswordValues"]));
            }
            set {
                this["FtpPasswordValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enable this if you\'d prefer to always use FTP when transferring mods")]
        public string FtpPreferredComment {
            get {
                return ((string)(this["FtpPreferredComment"]));
            }
            set {
                this["FtpPreferredComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FTP Transfers")]
        public string FtpPreferredName {
            get {
                return ((string)(this["FtpPreferredName"]));
            }
            set {
                this["FtpPreferredName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FtpPreferredValues {
            get {
                return ((string)(this["FtpPreferredValues"]));
            }
            set {
                this["FtpPreferredValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transfers only affect folders made by Quasar")]
        public string TransferQuasarFoldersOnlyComment {
            get {
                return ((string)(this["TransferQuasarFoldersOnlyComment"]));
            }
            set {
                this["TransferQuasarFoldersOnlyComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Manage all mods")]
        public string TransferQuasarFoldersOnlyName {
            get {
                return ((string)(this["TransferQuasarFoldersOnlyName"]));
            }
            set {
                this["TransferQuasarFoldersOnlyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TransferQuasarFoldersOnlyValues {
            get {
                return ((string)(this["TransferQuasarFoldersOnlyValues"]));
            }
            set {
                this["TransferQuasarFoldersOnlyValues"] = value;
            }
        }
    }
}
