[infos]
version = "0.9.6"

[paths]
arc = "sd:/Quasar/Default/arc"
umm = "sd:/Quasar/Default/Mods"

[updater]
server_ip = "178.62.31.147"
beta_updates = false

[logger]
logger_level = "Info"

[misc]
debug = false
